services:
  marp:
    build: .
    init: true
    volumes:
      - ./:/home/marp/app
    environment:
      - LANG=${LANG}
      - MARP_USER=1000:1000
    ports:
      - "8080:8080"
      - "37717:37717"
      - "8290:8290"
    command: -s /home/marp/app/markdown
